spring.application.name=msvc-productos
server.port=8003
server.servlet.context-path=/api/v1
spring.profiles.active=dev
# Database Configuration
spring.datasource.url=jdbc:h2:mem:productosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Logging
logging.level.com.ampuero.msvc.producto=INFO
logging.level.com.ampuero.msvc.producto.services.ProductoServiceImpl=DEBUG
logging.level.com.ampuero.msvc.producto.controllers.ProductoController=INFO
# CORS Configuration
cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:3000
springdoc.api-docs.enable=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html