# Dockerfile base reutilizable para los microservicios Spring Boot
FROM amazoncorretto:21-alpine

WORKDIR /app

# Copiar el artefacto generado por Maven
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

# Perfil por defecto para el stack docker-compose (puede sobrescribirse)
ENV SPRING_PROFILES_ACTIVE=docker
ENV JAVA_OPTS=""

# Entrada flexible para permitir flags adicionales (por ejemplo, -Xms512m)
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
