spring.application.name=msvc-auth
server.port=8001
spring.profiles.active=dev
# CORS Configuration
cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Connection pool (desarrollo)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1